### PR TITLE
Gnome 47

### PR DESCRIPTION
**Pull request by adaschma**
Ported to Gnome 47.

### CODE REVIEW

**Comment by adaschma** [comment]
Hi @blipk, it has been more than a week since I created this pull request. Did you have time to look at it? Just want to make sure it doesn't get forgotten or missed.

**Comment by blipk** [comment]
Hi @adaschma - I don't get notifications if I'm not assigned.

Also I only got Gnome 47 on my distro this week.

I will have a look soon enough

**Comment by blipk** [comment]
@adaschma 

This breaks some of the setting signal handling.

You shouldn't have to do that change to `this._refreshMenu()`

There is a loop in the settings schema listeners though in `sessionManager.js` with _saveOptions, _loadOptions and then the `changed::show-panel-indicator` signal watcher.

It seems they changed some of the signal handling works, and also calling refreshMenu there makes it worse. It also breaks something in the workspace manager, I had to add a guard for that or it crashes my whole system on X11.

I don't have time to debug this at the moment, I will check back if you're able to solve it.

**Comment by blipk** [comment]
Eh I messed up my commit on that guard and accidentally closed your PR.

This is still not working fully with V47 though - feel free to open another PR.


It's really getting to the point where I don't want to maintain this anymore as it needs a pretty big rewrite, there are a lot of looping conditions and hacky guards like this and the gnome-shell updates keep making it worse.

**Comment by adaschma** [comment]
> Hi @adaschma - I don't get notifications if I'm not assigned.

How would you like to be contacted in the future? As far as I can tell, I don't have the permissions to assign you.

> This breaks some of the setting signal handling.
> 
> You shouldn't have to do that change to `this._refreshMenu()`
> 
> There is a loop in the settings schema listeners though in `sessionManager.js` with _saveOptions, _loadOptions and then the `changed::show-panel-indicator` signal watcher.
> 
> It seems they changed some of the signal handling works, and also calling refreshMenu there makes it worse. It also breaks something in the workspace manager, I had to add a guard for that or it crashes my whole system on X11.
> 
> I don't have time to debug this at the moment, I will check back if you're able to solve it.

Sorry, I can't follow. How can I reproduce the bugs?

**Comment by blipk** [comment]
@adaschma The ping should usually work, I'm just pretty busy with some other things now.

The problem is on this line: https://github.com/blipk/Customised-Workspaces/blob/6c9338b2ddbe2576c7f5cf8dd458ed4b45d7e98a/worksets%40blipk.xyz/sessionManager.js#L253

If I disable the panel indicator from its menu, then try to re-enable it (either from overview or extension prefs) then as soon as I hit this line I get a bunch of NUL characters printed to my log file and my whole system freezes up.

I'm really not sure what the underlying issue is, but during debugging there is a lot of conflicts when setting and getting the gsettings values, I think if this can be resolved then the issue should solve itself or it's cause will become evident.

**Comment by blipk** [comment]
@adaschma 

I was right, the signal loop was freezing up my system.

I've added in some hackish stops to my ancient spaghetti code and it seems to be fixed now.

If you could please test and confirm that would be appreciated

**Comment by adaschma** [comment]
Works well. While I didn't have the problem of it freezing the system previously, I do notice that it reacts quicker now. Thank you.

**Pull request merged**
